channels:
- conda-forge
dependencies:
- python=3.11.0
- pip<=24.0
- pip:
  - mlflow==2.10.2
  - colorama==0.4.6
  - huggingface-hub==0.20.3
  - langchain==0.1.4
  - numpy==1.26.3
  - packaging==23.2
  - pathlib==1.0.1
  - psutil==5.9.8
  - pyyaml==6.0.1
  - requests==2.31.0
  - sqlalchemy==2.0.25
  - tornado==6.4
name: mlflow-env
